---
- hosts: webservers
  gather_facts: no
  sudo: yes
  roles:
    # 最新にupdate、必要なパッケージのインストール、時刻の設定
    #- base
    - { role: ../common-roles/base.raspbian, tags: raspbian } 
    - { role: ../common-roles/base.mac, tags: mac } 
    - { role: ../common-roles/base.ubuntu, tags: ubuntu } 
    - { role: ../common-roles/base.centos6, tags: [ 'centos', 'centos6' ] }
    - { role: ../common-roles/base.centos7, tags: centos7 }

    # ipv6 disable
    - { role: ../common-roles/staenker.ipv6-support, enabled: false, tags: ubuntu }

    # 個人ユーザ作成と鍵の登録
    - { role: ../common-roles/useradd.key.ubuntu, user_name: deploy, user_key: id_rsa.pub, tags: ubuntu }
    - { role: ../common-roles/useradd.key.centos6, user_name: deploy, user_key: id_rsa.pub, tags: [ 'centos', 'centos6' ] }
    - { role: ../common-roles/useradd.key.centos7, user_name: deploy, user_key: id_rsa.pub, tags: centos7 }

    # 個人ユーザの作成とパスワードの設定
    # 未完成。vars_prompt使って上手くやりたい。。
    #- { role: useradd.password, user_name: deploy }
