---
- hosts: webservers
  gather_facts: yes
  sudo: yes
  roles:


    # mysqlのインストール
    - {role: ../common-roles/ANXS.mysql, mysql_root_password: foobar }
    #- {role: ../common-roles/ANXS.mysql.centos7, mysql_root_password: foobar }
