---
- name: passengerに必要なパッケージをインストール
  yum: name={{ passenger_packages | join(",") }}

- name: ppassengerをインストール
  gem: name={{ item }} user_install=no executable={{ rbenv_root }}/shims/gem
  with_items: passenger_gems

- name: passenger module のインストール
  command: passenger-install-apache2-module --auto --languages=ruby

- name: バーチャルホスト用confファイルの配置
  template: src=passenger.tj2 dest=/etc/httpd/conf.d/passenger.conf

- name: apache再起動
  service: name=httpd state=restarted
