- hosts: all
  user: "{{ ansible_user }}"
  sudo: yes
  gather_facts: no
  tasks:
    - command: sudo ls /var/spool/cron/
      register: output

    #- debug: var=output
    - debug: var=output.stdout_lines
    #- debug: var=output.stderr

      #ignore_errors: True
