---
- hosts: all
  connection: local
  gather_facts: no
  roles:
    # create ec2 instance
    - { role: create.ec2.instance, image: ami-a1124fa0, instance_type: t2.micro, keypair: mypair group: securitygrp, region: ap-northeast-1 }
