- name: Install_Redmine
  hosts: server
  user: root
  roles:
    #for root
    #- { role: hostname, server_name: node }
    #- { role: Packages, www_port: 80, redmine_home: /home/redmine }
    #- user
    #for redmine
    - { role: ruby, ruby_ver: 2.2.0 }
    - { role: mariadb, mysql_root_password: password }
    - { role: redmine, mysql_redmine_password: password, mysql_redmine_database: redmine, redmine_ver: 3.0.0 }
#    - redmine-plugins

