---
- hosts: webservers
  gather_facts: no
  sudo: yes
  roles:

    # pipのインストール
    - {role: ../common-roles/ftakao2007.pip, tags: [ 'ubuntu', 'centos6', 'centos7' ]}

    # ansibleのインストール
    - {role: ../common-roles/ftakao2007.ansible.centos, tags: [ 'centos6', 'centos7' ] }
    - {role: ../common-roles/ftakao2007.ansible.ubuntu, tags: ubuntu }
