---
- hosts: webservers
  gather_facts: no
  sudo: yes
  roles:

    # pipのインストール
    #- {role: ../common-roles/ftakao2007.pip }

    # ansibleのインストール
    - {role: ../common-roles/ftakao2007.ansible.centos }
