---
- hosts: webservers
  gather_facts: no
  sudo: yes
  roles:

    # apacheのインストール
    - {role: ../common-roles/ftakao2007.apache.ubuntu, tags: ubuntu}
    - {role: ../common-roles/ftakao2007.apache.centos, tags: [ centos, centos7 ] }
