---
- hosts: webservers
  gather_facts: yes
  sudo: yes
  roles:

    # javaのインストール
    - {role: ../common-roles/geerlingguy.java.centos, java_packages: java-1.7.0-openjdk, tags: [ 'centos6', 'centos7' ] }
    - {role: ../common-roles/geerlingguy.java.ubuntu, java_packages: iopenjdk-7-jdk, tags: ubuntu }

