---
- hosts: webservers
  gather_facts: yes
  sudo: yes
  vars:
    jenkins_hostname: node
  roles:
    # javaのインストール
    - {role: ../common-roles/geerlingguy.java.centos, java_packages: java-1.7.0-openjdk, tags: [ 'centos6', 'centos7' ] }
    - {role: ../common-roles/geerlingguy.java.ubuntu, java_packages: openjdk-7-jdk, tags: ubuntu }

    # jenkinsのインストール
    - {role: ../common-roles/geerlingguy.jenkins, tags: ubuntu }
