---
- hosts: webservers
  gather_facts: no
  sudo: yes
  roles:

    # rbenvのインストール
    #- {role: ../common-roles/znzj.rbenv, rbenv_ruby_version: 2.2.2 }
    - {role: ../common-roles/znzj.rbenv.centos, rbenv_ruby_version: 2.2.2 }
