- hosts: all
  user: "{{ ansible_user }}"
  sudo: yes
  gather_facts: no
  tasks:
    - command: cat /etc/exports
      register: output

    - debug: var=output.stdout_lines

      #ignore_errors: True
