- hosts: all
  user: "{{ ansible_user }}"
  sudo: yes
  gather_facts: no
  tasks:
    - command: sudo ls -lh /var/lib/libvirt/images
      register: output

    - debug: var=output.stdout_lines

      #ignore_errors: True
