---
- hosts: webservers
  gather_facts: yes
  sudo: yes
  roles:
    ### ansibleインストール
    # pipのインストール
    - {role: ../common-roles/ftakao2007.pip }

    # ansibleのインストール
    - {role: ../common-roles/ftakao2007.ansible.centos }

    ### jenkinsインストール
    # javaのインストール
    #- {role: ../common-roles/geerlingguy.java.centos, java_packages: java-1.7.0-openjdk }

    # jenkinsのインストール
    #- {role: ../common-roles/geerlingguy.jenkins }

  tasks:
    - name: リポジトリのダウンロード
      git: repo=https://github.com/ftakao2007/ansible.git dest=~/ansible update=no
      sudo: no

    #- name: ansibleテスト
    #  command: ansible-playbook -i "127.0.0.1," ~/ansible/no-roles-test/execute_echo.yml -vvv -k -c paramiko
